### PR TITLE
`json`: add `--jaq` option to allow jq-like filtering & test

### PR DESCRIPTION
**Pull request by rzmk**
image

- Adds a `--jaq <filter>` option using [jaq](https://github.com/01mf02/jaq) (adds `jaq-interpreter` and `jaq-parser` crates) to allow users to provide a jq-like filter before attempting to parse the JSON data in its intended format.
- Updates the usage text with more information regarding expected format, and examples.
- Adds a basic test for non-nested data using `--jaq`.

### CODE REVIEW

**Comment by jqnatividad** [comment]
Good stuff @rzmk!  It seems jaq and jql are functionally equivalent.  jql is used by the `fetch` commands to parse JSON responses.

Can you check to see which one is better and then we can just use one crate for both `json` and the `fetch` commands?

**Comment by rzmk** [comment]
Excerpt from jaq's README:

> I drew inspiration from another Rust program, namely jql. However, unlike jql, jaq aims to closely imitate jq's syntax and semantics. This should allow users proficient in jq to easily use jaq.

Not sure what criteria to base as to which one is better.

**Comment by jqnatividad** [comment]
Performance above all. But the point that jaq uses jq syntax/semantics is a good bonus... so let's adopt `jaq` for the `fetch` commands as well...

**Comment by rzmk** [comment]
@jqnatividad I think that may be a separate issue to add.

Also any thoughts on how we'd want to perform benchmarks to compare?

**Comment by jqnatividad** [comment]
OK... can you create an issue for it?

As for a quick benchmark to compare jql vs jaq, jql has a quick benchmark that should be easily adaptable to jaq.

https://github.com/yamafaktory/jql/blob/main/PERFORMANCE.md

Can you take a crack at it? I would have done it myself but I'm on a customer-facing deadline ATM...

**Comment by rzmk** [comment]
jaq-jql-bench-demo

```sh
#! /bin/bash

# Test 1
jaq_test_1() { echo '[1, [2], [[3]]]' | jaq 'flatten'; }
export -f jaq_test_1
jql_test_1() { echo '[1, [2], [[3]]]' | jql '..'; }
export -f jql_test_1
hyperfine --warmup 3 --shell=bash jaq_test_1 jql_test_1

# Test 2
jaq_test_2() { echo '[1, 2, 3]' | jaq '.[0]'; }
export -f jaq_test_2
jql_test_2() { echo '[1, 2, 3]' | jql '[0]'; }
export -f jql_test_2
hyperfine --warmup 3 --shell=bash jaq_test_2 jql_test_2

# Test 3
jaq_test_3() { echo '{ "foo": "bar" }' | jaq '.foo'; }
export -f jaq_test_3
jql_test_3() { echo '{ "foo": "bar" }' | jql '"foo"'; }
export -f jql_test_3
hyperfine --warmup 3 --shell=bash jaq_test_3 jql_test_3

# Test 4
jaq_test_4() { cat github-repositories.json | jaq -r '[.[] | {name: .name, url: .url, language: .language, stargazers_count: .stargazers_count, watchers_count: .watchers_count}]' > /dev/null; }
export -f jaq_test_4
jql_test_4() { cat github-repositories.json | jql '|>{"name", "url", "language", "stargazers_count", "watchers_count"}' > /dev/null; }
export -f jql_test_4
hyperfine --warmup 3 --shell=bash jaq_test_4 jql_test_4

# hyperfine --warmup 3 --shell=bash jaq_test_1 jql_test_1 jaq_test_2 jql_test_2 jaq_test_3 jql_test_3 jaq_test_4 jql_test_4
```

**Comment by jqnatividad** [comment]
So `jql` is faster. However, `jaq` using `jq` semantics is very attractive.

And with `jq` being the de facto JSON-wrangling command-line tool, I say let's go with `jaq`.

As it is, 0.129.0 is delayed, so I'll just merge this PR and defer moving the `fetch` commands to use `jaq` for a future release.

**Pull request merged**
